apiVersion: v1
kind: Namespace
metadata:
  name: roboshop-ns
  labels:
    project: roboshop
    env: dev
---

apiVersion: V1
kind: Pod
metadata:
  name: roboshop-pod
  labels:
    project: roboshop
    env: dev