apiVersion: v1
kind: Pod
metadata: 
  name: roboshop-pod
  labels:
    purpose: robo-pod
    project: roboshop
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx 
  - name: almalinux
    iamge: almalinux:9   