apiVersion: v1
kind: Pod
metadata: 
  namespace: roboshop-ns
  name: roboshop-pod
  labels:
    purpose: robo-pod
    project: roboshop
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx  