apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop-ns
  name: resources-robo
  labels:
    name: pod-resources
    project: roboshop
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx  
    resources:
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "250m"
        memory: "100Mi"    