apiVersion: v1
kind: Pod
metadata:
  name: resources
  namespace: roboshop-ns
  labels:
    name: pod-resources
    project: roboshop
    enc: dev
spec:
  containers:
  - name: nginx
    image: nginx  
    resources:
      requests:
        cpu: "100m"
        memory: "68mi"
      limits:
        cpu: "250m"
        memory: "100mi"    