apiVersion: v1
kind: Pod
metadata: 
  name: env-demo
  labels: 
    purpose: env-demorobo
    env: dev
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: "k8"
    - name: trainer
      value: "siva"      