apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels: 
    name: service-demo
spec:
  selectors:
    purpose: service-demo
    project: roboshop
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetport: 80

---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    purpose: service-demo
    project: roboshop
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx    