apiVersion: v1
kind: Service
metadata:
  name: demo-loadbalancer
  labels:
    name: lb-demo
spec:
  type: loadBalancer
  selector:
    name: loadbalancer-demo
    project: roboshop
    env: dev
  ports:
   - protocol: TCP
     port: 80
     targerPort: 80

---

apiVerison: v1
kind: Pod
metadata:
  name: lb-pod
  labels:
    name: loadbalancer-demo
    project: roboshop
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx    
