apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-ReplicaSet
  labels:
    purpose: demo-rs 
    project: roboshop
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      name: rs
      project: roboshop
      env: dev

  template:
    metadata:
      labels:
        name: rs
        project: roboshop
        env: dev
    spec:
    containers:
      - name: nginx
        image: nginx        