apiVersion: apps/v1
kind: replicaset
metadata:
  name: replica-demo
  labels:
    purpose: demo-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      purpose: replica-demo
      env: dev
template:
  metadata:
    name: nginx-replica
    labels:
      project: roboshop
      purpose: replica-demo
      env: dev
  spec:
    containers:
    - name: nginx
      image: nginx    